#!/usr/bin/env python

import inventory_remove
import inventory_add
import inventory_modifyexpiry
import inventory_modifyname
import inventory_daily
import inventory_printout
import inventory_addname
import inventory_xmlout
import inventory_grabcronometer
import inventory_grabrecipes
import inventory_randomjson

import argparse

parser = argparse.ArgumentParser(description='Read and store product information from upc codes.')
parser.add_argument('action', action='store', help='The action we want to perform; can be one of: add, addmanually, modifyexpiry, modifyname, remove, printout, xmlout, or daily. Select add to begin!')

args = parser.parse_args()
#print args.accumulate(args.integers)
print "You have selected \"" + args.action + "\"."

{'add' : inventory_add.main, 'addmanually' : inventory_addname.main, 'grabcronometer' : inventory_grabcronometer.main, 'grabrecipes' : inventory_grabrecipes.main, 'modifyexpiry' : inventory_modifyexpiry.main, 'modifyname' : inventory_modifyname.main, 'daily' : inventory_daily.main, 'randomjson' : inventory_randomjson.main, 'remove' : inventory_remove.main, 'printout' : inventory_printout.main, 'xmlout' : inventory_xmlout.main}[args.action]()

